#cloud-config

coreos:
    etcd2:
        advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
        initial-advertise-peer-urls: http://$private_ipv4:2380
        listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
        listen-peer-urls: http://$private_ipv4:2380
    units:
        - name: etcd2.service
          command: start
        - name: fleet.service
          command: start
        - name: starzd.service
          command: start
          content: |
            [Unit]
            Description=starzd
            After=docker.service
            Requires=docker.service

            [Service]
            TimeoutStartSec=0
            ExecStartPre=-/usr/bin/docker kill dmmcquay/starz:v1
            ExecStartPre=-/usr/bin/docker rm dmmcquay/starz:v1
            ExecStartPre=/usr/bin/docker pull dmmcquay/starz:v1
            ExecStart=/usr/bin/docker run -p 80:8000 \
                              -e STARZ_CLIENTSECRET= ADD_CLIENTSECRET\
                              -e STARZ_CLIENTID=ADD_CLIENTID \
                              -e STARZ_APITOKEN=ADD_API_TOKEN \
                              dmmcquay/starz:v1

            [X-Fleet]
            Global=true
